apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goat-api
  namespace: ${NAMESPACE}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goat-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: goat-api
    spec:
      containers:
        - image: ${DOCKER_IMAGE}
          imagePullPolicy: Always
          name: goat-api
          envFrom:
            - configMapRef:
                name: api-config
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 60
            periodSeconds: 120
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 5000
            initialDelaySeconds: 20
            timeoutSeconds: 60
            periodSeconds: 120
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: goat-api
  namespace: ${NAMESPACE}
spec:
  ports:
    - port: 80
      targetPort: 5000
  type: NodePort
  selector:
    app: goat-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: ${NAMESPACE}
  labels:
    app: goat-api
data:
  PROJECT_NAME: goat
  SERVER_NAME: ${DOMAIN}
  SERVER_HOST: https://${DOMAIN}
  POSTGRES_SERVER: postgres-service
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  SENTRY_DSN: ${SENTRY_DSN}
  NAMESPACE: ${NAMESPACE}
  FIRST_ORGANIZATION: ${FIRST_ORGANIZATION}
  FIRST_SUPERUSER_NAME: ${FIRST_SUPERUSER_NAME}
  FIRST_SUPERUSER_SURNAME: ${FIRST_SUPERUSER_SURNAME}
  FIRST_SUPERUSER_EMAIL: ${FIRST_SUPERUSER_EMAIL}
  FIRST_SUPERUSER_PASSWORD: ${FIRST_SUPERUSER_PASSWORD}
  EMAILS_FROM_EMAIL: ${EMAILS_FROM_EMAIL}
  SMTP_USER: ${EMAILS_FROM_EMAIL}
  SMTP_PASSWORD: ${SMTP_PASSWORD}
  API_SECRET_KEY: ${API_SECRET_KEY}
  R5_HOST: ${R5_HOST}
  R5_AUTHORIZATION: ${R5_AUTHORIZATION}

  # ---

# apiVersion: batch/v1
# kind: Job
# metadata:
#   namespace: ${NAMESPACE}
#   name: goat-api-migrations
#   labels:
#     app: goat-api
# spec:
#   template:
#     spec:
#       containers:
#         - name: migration-container
#           image: ${DOCKER_IMAGE}
#           command: ['alembic', 'upgrade', 'head']
#           envFrom:
#             - configMapRef:
#                 name: api-config
#       restartPolicy: Never
#   backoffLimit: 3
