language: node_js
node_js: stable
branches:
  only:
    - master
    - development
install:
  - "cd $TRAVIS_BUILD_DIR/app/client"
  - "npm install"
script:
  - "cd $TRAVIS_BUILD_DIR/app/client"
  - "npm run build"
