language: generic
sudo: required
dist: trusty
services:
  - docker
branches:
  only:
    - master
    - development
    - test_travis
script:
  - make release-docker-image -e COMPONENT=client
  - make release-docker-image -e COMPONENT=api
after_success:
  - make after-success
notifications:
  email:
    on_success: never
    on_failure: always
