language: generic
sudo: required
dist: trusty
services:
  - docker
branches:
  only:
    - master
    - development
script:
  - cd $TRAVIS_BUILD_DIR
  - cd ./scripts
  - ls
  - chmod +x docker-publish-travis.sh
deploy:
  provider: script
  script: docker-publish-travis.sh
  skip_cleanup: true
