language: generic
sudo: required
dist: trusty
services:
  - docker
branches:
  only:
    - master
    - development
    - beta
    - test_travis
stages:
  - name: build
    if: fork = false
  - name: release
    if: type = push AND fork = false
  - name: development-deploy
    if: branch = development AND type = push AND fork = false
  - name: beta-deploy
    if: branch = beta AND type = push AND fork = false
jobs:
  include:
    - stage: build
      script:
        - make build-database-docker-image
        - make build-docker-image -e COMPONENT=client
        - make build-docker-image -e COMPONENT=api
        - make build-docker-image -e COMPONENT=geoserver
        - make build-docker-image -e COMPONENT=print
        - make build-docker-image -e COMPONENT=mapproxy
    - stage: release
      script:
        - make release-database-docker-image
        - make release-docker-image -e COMPONENT=client
        - make release-docker-image -e COMPONENT=api
        - make release-docker-image -e COMPONENT=geoserver
        - make release-docker-image -e COMPONENT=print
        - make release-docker-image -e COMPONENT=mapproxy
    - stage: development-deploy
      script:
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        - make setup-kube-config
        - make deploy-postgres-server
        - make deploy -e COMPONENT=api
        - make deploy -e COMPONENT=client
        - make deploy -e COMPONENT=geoserver
        - make deploy -e COMPONENT=print
        - make deploy -e COMPONENT=mapproxy
    - stage: beta-deploy
      script:
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        - make setup-kube-config
        - make deploy -e COMPONENT=postgres -e NAMESPACE=beta -e DOMAIN=beta.open-accessibility.org
        - make deploy -e COMPONENT=api -e NAMESPACE=beta -e DOMAIN=beta.open-accessibility.org
        - make deploy -e COMPONENT=client -e NAMESPACE=beta -e DOMAIN=beta.open-accessibility.org
        - make deploy -e COMPONENT=geoserver -e NAMESPACE=beta -e DOMAIN=beta.open-accessibility.org
        - make deploy -e COMPONENT=print -e NAMESPACE=beta -e DOMAIN=beta.open-accessibility.org
        - make deploy -e COMPONENT=mapproxy -e NAMESPACE=beta -e DOMAIN=beta.open-accessibility.org
after_success:
  - make after-success
notifications:
  email:
    on_success: never
    on_failure: always
