language: generic
node_js: stable
sudo: required
dist: trusty
services:
  - docker
branches:
  only:
    - master
    - development
script:
  - cd $TRAVIS_BUILD_DIR
  - chmod -R a+x scripts
  - ./scripts/docker-publish-travis.sh
