language: generic
sudo: required
dist: trusty
services:
  - docker
branches:
  only:
    - master
    - development
    - test_travis
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/docker-public-travis.sh
