language: generic
sudo: required
dist: trusty
services:
  - docker
branches:
  only:
    - master
    - development
    - beta
    - test_travis

jobs:
  include:
    #BUILD STAGE
    - &build
      stage: build
      if: type = pull_request
      env: COMPONENT=client
      name: concat("Build ", env(COMPONENT))
      script:
        - make build-docker-image
    - <<: *build
      env: COMPONENT=api
    - <<: *build
      env: COMPONENT=geoserver
    - <<: *build
      env: COMPONENT=print
    - <<: *build
      env: COMPONENT=mapproxy

    #RELEASE STAGE
    - &release
      stage: release
      if: type = push AND fork = false
      env: COMPONENT=client
      name: concat("Release of ", env(COMPONENT))
      script:
        - make release-docker-image -e COMPONENT=$COMPONENT
    - <<: *release
      env: COMPONENT=api
    - <<: *release
      env: COMPONENT=geoserver
    - <<: *release
      env: COMPONENT=print
    - <<: *release
      env: COMPONENT=mapproxy

    #DEV DEPLOY STAGE
    - &development-deploy
      stage: development-deploy
      if: branch = development AND type = push AND fork = false
      env: COMPONENT=client
      name: concat("Development deploy of ", env(COMPONENT))
      script:
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        - make setup-kube-config
        - make deploy-postgres-server
        - make deploy -e COMPONENT=$COMPONENT
    - <<: *development-deploy
      env: COMPONENT=api
    - <<: *development-deploy
      env: COMPONENT=geoserver
    - <<: *development-deploy
      env: COMPONENT=print
    - <<: *development-deploy
      env: COMPONENT=mapproxy

    #BETA DEPLOY STAGE
    - &beta-deploy
      stage: beta-deploy
      if: branch = beta AND type = push AND fork = false
      env: COMPONENT=client
      name: concat("Beta deploy of ", env(COMPONENT))
      script:
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        - make setup-kube-config
        - make deploy-postgres-server
        - make deploy -e COMPONENT=$COMPONENT -e DOMAIN=beta.open-accessibility.org
    - <<: *beta-deploy
      env: COMPONENT=api
    - <<: *beta-deploy
      env: COMPONENT=geoserver
    - <<: *beta-deploy
      env: COMPONENT=print
    - <<: *beta-deploy
      env: COMPONENT=mapproxy

after_success:
  - make after-success
notifications:
  email:
    on_success: never
    on_failure: always
