language: generic
sudo: required
dist: trusty
services:
  - docker
branches:
  only:
    - master
    - development
script:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x ./scripts/docker-publish-travis.sh
deploy:
  provider: script
  script: ./scripts/docker-publish-travis.sh
  skip_cleanup: true
