language: node_js
node_js: stable
sudo: required
dist: trusty
services:
  - docker
branches:
  only:
    - master
    - development
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/docker-publish-travis.sh
