language: generic
sudo: required
dist: trusty
services:
  - docker
branches:
  only:
    - master
    - development
    - test_travis
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/docker-public-travis.sh
after_success:
  - ./scripts/after-success.sh
notifications:
  email:
    on_success: never
    on_failure: always
