language: generic
sudo: required
dist: trusty
services:
  - docker
branches:
  only:
    - master
    - development
    - beta
    - test_travis
stages:
  - name: release

  - name: development-deploy
    if: branch = development AND type = push AND fork = false
  - name: beta-deploy
    if: branch = beta AND type = push AND fork = false
jobs:
  include:
    #BUILD STAGE
    - &build
      stage: build
      if: type = pull_request
      env: COMPONENT=client
      script:
        - make build-docker-image
    - <<: *build
      env: COMPONENT=api
    - <<: *build
      env: COMPONENT=geoserver
    - <<: *build
      env: COMPONENT=print
    - <<: *build
      env: COMPONENT=mapproxy
    #RELEASE STAGE
    - &release
      stage: release
      if: type = push AND fork = false
      env: COMPONENT=client
      script:
        - make release-docker-image
    - <<: *release
      env: COMPONENT=api
    - <<: *release
      env: COMPONENT=geoserver
    - <<: *release
      env: COMPONENT=print
    - <<: *release
      env: COMPONENT=mapproxy
      #DEV DEPLOY
    # - stage: development-deploy
    #   script:
    #     - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
    #     - make setup-kube-config
    #     - make deploy-postgres-server
    #     - make deploy -e COMPONENT=api
    #     - make deploy -e COMPONENT=client
    #     - make deploy -e COMPONENT=geoserver
    #     - make deploy -e COMPONENT=print
    #     - make deploy -e COMPONENT=mapproxy
    #BETA DEPLOY
    # - stage: beta-deploy
    #   script:
    #     - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
    #     - make setup-kube-config
    #     - make deploy -e COMPONENT=postgres -e NAMESPACE=beta -e DOMAIN=beta.open-accessibility.org
    #     - make deploy -e COMPONENT=api -e NAMESPACE=beta -e DOMAIN=beta.open-accessibility.org
    #     - make deploy -e COMPONENT=client -e NAMESPACE=beta -e DOMAIN=beta.open-accessibility.org
    #     - make deploy -e COMPONENT=geoserver -e NAMESPACE=beta -e DOMAIN=beta.open-accessibility.org
    #     - make deploy -e COMPONENT=print -e NAMESPACE=beta -e DOMAIN=beta.open-accessibility.org
    #     - make deploy -e COMPONENT=mapproxy -e NAMESPACE=beta -e DOMAIN=beta.open-accessibility.org
after_success:
  - make after-success
notifications:
  email:
    on_success: never
    on_failure: always
