language: generic
sudo: required
dist: trusty
services:
  - docker
branches:
  only:
    - master
    - development
    - test_travis
before_script:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt` && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
script:
  - make release-docker-image -e COMPONENT=client
  - make release-docker-image -e COMPONENT=api
  - make deploy-postgres-server
after_success:
  - make after-success
notifications:
  email:
    on_success: never
    on_failure: always
