version: "3.9"

services:
  api:
    command:
      [
        "sh",
        "-c",
        "python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"
      ]
    # command: bash -c "while true; do sleep 1; done" # Infinite loop to keep container live doing nothing
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_api.loadbalancer.server.port=8000"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_api.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_api.entrypoints=web"
    ports:
      - "8000:8000"
      - "5678:5678"
    networks:
      proxy:
