version: "3.7"

networks:
  proxy:

services:
  traefik:
    image: "traefik:1.7.2-alpine"
    container_name: "traefik"
    ports:
      - "80:80" # - Default Port
      - "443:443" # - SSL Port
      - "31951:31951" # - Mapproxy
      - "8000:8000" # - Traefik UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/config/traefik.toml:/etc/traefik/traefik.toml
      - ./app/config/ssl:/ssl
    labels:
      - "traefik.backend=traefik"
      - "traefik.frontend.entryPoints=traefik-ui"
      - "traefik.frontend.rule=Host:localhost;"
      - "traefik.port=8080"
      - "traefik.enable=true"
    networks:
      proxy:

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./app/client
    image: goat-client
    volumes:
      - /app/node_modules
      - ./app/client:/app
    container_name: goat-client
    labels:
      - "traefik.backend=client"
      - "traefik.frontend.entryPoints=https,http"
      - "traefik.frontend.rule=Host:localhost;"
      - "traefik.port=5000"
      - "traefik.enable=true"
    networks:
      proxy:

  api:
    build:
      context: ./app/api
    image: goat-api
    volumes:
      - /app/node_modules
      - ./app/api:/app
    container_name: goat-api
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.entryPoints=https,http"
      - "traefik.frontend.rule=Host:localhost;PathPrefix:/api"
      - "traefik.port=3000"
      - "traefik.enable=true"
    networks:
      proxy:

  geoserver:
    build:
      context: ./app/geoserver
    image: goat-geoserver:2.15
    volumes:
      - ./app/geoserver/gs-catalog:/opt/geoserver_data/
    container_name: goat-geoserver
    restart: on-failure
    labels:
      - "traefik.backend=geoserver"
      - "traefik.frontend.entryPoints=https,http"
      - "traefik.frontend.rule=Host:localhost;PathPrefix:/geoserver"
      - "traefik.port=8080"
      - "traefik.enable=true"
    networks:
      proxy:

  print:
    image: camptocamp/mapfish_print:3.16
    volumes:
      - ./app/print/templates:/usr/local/tomcat/webapps/ROOT/print-apps
    container_name: goat-print
    labels:
      - "traefik.backend=print"
      - "traefik.frontend.entryPoints=https,http"
      - "traefik.frontend.rule=Host:localhost;PathPrefix:/print"
      - "traefik.port=8080"
      - "traefik.enable=true"
    networks:
      proxy:

  mapproxy:
    image: kartoza/mapproxy
    volumes:
      - ./app/mapproxy:/mapproxy
    container_name: goat-mapproxy
    labels:
      - "traefik.backend=mapproxy"
      - "traefik.frontend.entryPoints=mapproxy"
      - "traefik.frontend.rule=Host:localhost;"
      - "traefik.port=8080"
      - "traefik.enable=true"
    networks:
      proxy:

  postgres:
    build:
      context: ./app/database
    image: goat-database
    container_name: goat-database
    volumes:
      - ./app/database/postgres_data:/var/lib/postgresql/data
      - ./app/database:/opt
    ports:
      - "65432:5432"
    networks:
      proxy:
