DATABASE:
  HOST: "localhost"
  PORT: 5432
  DB_NAME: "goat"
  USER: "goat"
  PASSWORD: "earlmanigault"

DATA_SOURCE:  
  OSM_DOWNLOAD_LINK: "https://download.geofabrik.de/europe/germany/bayern/oberbayern-latest.osm.pbf"
  BUFFER_BOUNDING_BOX: 0.045 #in degree (default: approx. 3km)
  POPULATION: "extrapolation" 
  #extrapolation ==> census.shp + landuse.shp needed as input
  #disaggregation ==> landuse.shp needed as input + high-resolution population input data + high completness number of floors
  #custom_population ==> population.shp custom population data needed  

