apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goat-geoserver
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goat-geoserver
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: goat-geoserver
    spec:
      containers:
      - image: ${DOCKER_IMAGE}
        imagePullPolicy: IfNotPresent
        name: goat-geoserver
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 256Mi
            cpu: 200m
          limits:
            memory: 512Mi
            cpu: 300m
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: '/$2'
  name: goat-geoserver
  namespace: ${NAMESPACE}
spec:
  rules:
    - host: ${DOMAIN}
      http:
        paths:
          - backend:
              serviceName: goat-geoserver
              servicePort: 80
            path: /geo-server(/|$)(.*)
  tls:
  - hosts:
    - ${DOMAIN}
    secretName: letsencrypt-prod
---
apiVersion: v1
kind: Service
metadata:
  name: goat-geoserver
  namespace: ${NAMESPACE}
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: goat-geoserver
