apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: ${NAMESPACE}
stringData:
  accessKeyID: ${DO_SPACES_ACCESS_KEY_ID}
  secretAccessKey: ${DO_SPACES_SECRET_ACCESS_KEY}
  endpoint: \"https://goat-data.fra1.digitaloceanspaces.com\"
  region: \"\" # If not on S3, set it to ""
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-s3
  namespace: ${NAMESPACE}
provisioner: ch.ctrox.csi.s3-driver
parameters:
  mounter: rclone
  csi.storage.k8s.io/provisioner-secret-name: csi-s3-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: csi-s3-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: csi-s3-secret
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: csi-s3-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system