name: "Bug report form 🐛"
description: "Thank you for reporting a bug!"
labels: Bug
title: [BUG] 
body:
- type: textarea
  attributes:
    label: Summary 📃
    description: <!--- Provide a general summary of the issue in the Title above -->
    value: summary
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behaviour ✔
    description: <!--- Tell us what should happen -->
    value: expected behaviour
  validations:
    required: true
- type: textarea
  attributes:
    label: Current Behaviour 🔦
    description: <!--- Tell us what happens instead of the expected behavior -->
    value: current behaviour
  validations:
    required: true
- type: textarea
  attributes:
    label: Possible Solution 💡
    description: <!--- Not obligatory, but suggest a fix/reason for the bug, -->
    value: possible solution
- type: textarea
  attributes:
    label: Steps to reproduce 👣
    description: |
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.
    value: steps to reproduce
  validations:
    required: true
- type: textarea
  attributes:
    label: Possible Implementation 📐
    description: <!--- Not obligatory, but suggest an idea for implementing addition or change -->
    value: possible implementation
