name: "Bug report form 🐛"
description: "Thank you for reporting a bug!"
labels: Bug
title: [BUG] 
body:
- type: textarea
  attributes:
    label: Summary 📃
#     description: 
    value: <!--- Provide a general summary of the issue in the Title above -->
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behaviour ✔
#     description: 
    value: <!--- Tell us what should happen -->
  validations:
    required: true
- type: textarea
  attributes:
    label: Current Behaviour 🔦
#     description: 
    value: <!--- Tell us what happens instead of the expected behavior -->
  validations:
    required: true
- type: textarea
  attributes:
    label: Possible Solution 💡
#     description: 
    value: <!--- Not obligatory, but suggest a fix/reason for the bug, -->
- type: textarea
  attributes:
    label: Steps to reproduce 👣
#     description: steps to reproduce
    value: |
         <!--- Provide a link to a live example, or an unambiguous set of steps to -->
         <!--- reproduce this bug. Include code to reproduce, if relevant -->
         1.
         2.
         3.
         4.
  validations:
    required: true
- type: textarea
  attributes:
    label: Possible Implementation 📐
    value: <!--- Not obligatory, but suggest an idea for implementing addition or change -->
