networks:
  proxy:
    name: goat

services:
  goat-dev:
    depends_on:
      - rabbitmq
      - redis
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: goat-dev
    volumes:
      - .:/app
    networks:
      proxy:
