name: "Lint"
on:
  workflow_call:
    inputs:
      web:
        type: boolean
        description: "Whether to run web linting"
        required: false
        default: true

      python:
        type: boolean
        description: "Whether to run python linting"
        required: false
        default: true


jobs:
  web:
    runs-on: ubuntu-latest
    if: ${{ inputs.web }}
    steps:
      - name: 游닌 Checkout
        uses: actions/checkout@v4

      - name: 游닌 Checkout PR
        uses: plan4better/.github/.github/actions/pr-git-checkout@main

      - name: 游닌 Monorepo install
        uses: plan4better/.github/.github/actions/pnpm-install@main
        with:
          enable-corepack: true
          cwd: ${{ github.workspace }}

      - name: 游댧 Run linting
        run: bash ${{ github.workspace }}/scripts/lint-web.sh

      - name: 游댧 Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          report-json: ${{ github.workspace }}/lint-results/eslint_report.json
          only-pr-files: false

      - name: 游댧 Upload ESLint report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: ${{ github.workspace }}/lint-results

  python:
    runs-on: ubuntu-latest
    if: ${{ inputs.python }}
    steps:
      - name: 游닌 Checkout
        uses: actions/checkout@v4

      - name: 游닌 Checkout PR
        uses: plan4better/.github/.github/actions/pr-git-checkout@main

      - name: 游냀 Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.4"
          enable-cache: true

      - name: 游냀 Install Dependencies
        run: uv sync --frozen --all-packages
        working-directory: ${{ github.workspace }}

      - name: 游댧 Run linting
        run: uv run bash scripts/lint-python.sh
        working-directory: ${{ github.workspace }}
