name: "PR"

on:
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  file-changes:
    name: file-changes
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  pr-base:
    name: pr-base
    uses: "plan4better/.github/.github/workflows/reusable-pr-base.yml@main"
    permissions:
      contents: none
      issues: read
      pull-requests: write
    secrets: inherit

  lint:
    name: lint
    needs: file-changes
    uses: ./.github/workflows/lint.yml
    secrets: inherit
    with:
      web: true
      python: true


  build-goat:
    name: build
    needs: file-changes
    if: ${{ needs.file-changes.outputs.web == 'true' || needs.file-changes.outputs.storybook == 'true' }}
    uses: ./.github/workflows/production-build.yml
    secrets: inherit

  analyze-goat:
    name: analyze-goat
    needs: build-goat
    uses: ./.github/workflows/nextjs-bundle-analysis.yml
    secrets: inherit

  build-keycloak:
    name: build-keycloak
    needs: file-changes
    if: ${{ needs.file-changes.outputs.keycloak-theme == 'true' }}
    uses: ./.github/workflows/keycloak-build.yml

  required:
    needs: [lint, build-goat, analyze-goat, build-keycloak]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1
