name: "Release"

on:
  release:
    types: [published]
  push:
    branches: [main]
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  file-changes:
    name: file-changes
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  lint:
    name: lint
    needs: file-changes
    uses: ./.github/workflows/lint.yml
    secrets: inherit
    with:
      web: true
      python: false

  release-docker-web:
    needs: [file-changes, lint]
    if: needs.file-changes.outputs.web == 'true' || startsWith(github.ref, 'refs/tags/v')
    uses: goat-community/.github/.github/workflows/reusable-docker-build.yml@main
    permissions:
      contents: read
      packages: write
      pull-requests: write
    with:
      dockerhub-enable: false
      ghcr-enable: true
      push: ${{ github.event_name != 'pull_request' }}
      file: ./apps/web/Dockerfile
      platforms: linux/amd64,linux/arm64
      image-names: |
        ghcr.io/${{ github.repository }}/web

  release-docker-geoapi:
    needs: [file-changes, lint]
    if: needs.file-changes.outputs.geoapi == 'true' ||
        startsWith(github.ref, 'refs/tags/v')
    uses: goat-community/.github/.github/workflows/reusable-docker-build.yml@main
    permissions:
      contents: read
      packages: write
      pull-requests: write
    with:
      dockerhub-enable: false
      ghcr-enable: true
      push: ${{ github.event_name != 'pull_request' }}
      file: ./apps/geoapi/Dockerfile
      platforms: linux/amd64,linux/arm64
      image-names: |
        ghcr.io/${{ github.repository }}/geoapi

  release-docker-storybook:
    needs: [file-changes, lint]
    if: needs.file-changes.outputs.storybook == 'true' || startsWith(github.ref, 'refs/tags/v')
    uses: goat-community/.github/.github/workflows/reusable-docker-build.yml@main
    permissions:
      contents: read
      packages: write
      pull-requests: write
    with:
      dockerhub-enable: false
      ghcr-enable: true
      push: ${{ github.event_name != 'pull_request' }}
      file: ./apps/storybook/Dockerfile
      platforms: linux/amd64,linux/arm64
      image-names: |
        ghcr.io/${{ github.repository }}/storybook

  release-docker-docs:
    needs: [file-changes, lint]
    if: needs.file-changes.outputs.docs == 'true' || startsWith(github.ref, 'refs/tags/v')
    uses: goat-community/.github/.github/workflows/reusable-docker-build.yml@main
    permissions:
      contents: read
      packages: write
      pull-requests: write
    with:
      dockerhub-enable: false
      ghcr-enable: true
      push: ${{ github.event_name != 'pull_request' }}
      file: ./apps/docs/Dockerfile
      platforms: linux/amd64,linux/arm64
      image-names: |
        ghcr.io/${{ github.repository }}/docs

  release-keycloak-theme:
    needs: [file-changes, lint]
    if: needs.file-changes.outputs.keycloak-theme == 'true' || startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/keycloak-build.yml
    secrets: inherit
    with:
      keycloak-theme-artifact-id: "p4b-keyclok-theme-${{ needs.file-changes.outputs.sha-short}}"
      push: true
